# Generated by Django 4.2.30 on 2026-09-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DEF', 'Защитник'), ('MID', 'Полузащитник'), ('ATT', 'Нападающий')], max_length=3)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('matches', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('photo', models.URLField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='appname.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'Предстоящий'), ('LIVE', 'Идёт'), ('FINISHED', 'Завершён')], max_length=20)),
                ('possession_home', models.PositiveIntegerField(default=50)),
                ('possession_away', models.PositiveIntegerField(default=50)),
                ('shots_home', models.PositiveIntegerField(default=0)),
                ('shots_away', models.PositiveIntegerField(default=0)),
                ('shots_on_target_home', models.PositiveIntegerField(default=0)),
                ('shots_on_target_away', models.PositiveIntegerField(default=0)),
                ('corners_home', models.PositiveIntegerField(default=0)),
                ('corners_away', models.PositiveIntegerField(default=0)),
                ('fouls_home', models.PositiveIntegerField(default=0)),
                ('fouls_away', models.PositiveIntegerField(default=0)),
                ('yellow_home', models.PositiveIntegerField(default=0)),
                ('yellow_away', models.PositiveIntegerField(default=0)),
                ('red_home', models.PositiveIntegerField(default=0)),
                ('red_away', models.PositiveIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='appname.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='appname.team')),
            ],
        ),
    ]
